# Generated by Django 4.1.4 on 2023-04-18 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_patient_data_continous_sneezing'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appuser',
            name='medical_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='yo', max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sex',
            field=models.CharField(default='hi', max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='25', max_length=50),
        ),
    ]
